# Generated by Django 5.1.4 on 2025-01-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_created_at_book_is_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
